"""add clients, retainers, retainer_requests, email_logs, job_runs; project completed_at/followup_sent_at; invoice retainer_id

Revision ID: 1b427d4e91de
Revises: af5fb8bf892e
Create Date: 2026-09-17 00:04:25.430758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b427d4e91de'
down_revision = 'af5fb8bf892e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('followup_opt_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=60), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', 'run_date', name='uq_job_runs_job_date')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('to_name', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retainer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=160), nullable=False),
    sa.Column('monthly_amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_day', sa.Integer(), nullable=False),
    sa.Column('next_invoice_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retainer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('quote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_invoices_retainer_id', 'retainers', ['retainer_id'], ['id'])
        # Every existing row today is kind in ('deposit','balance') with
        # quote_id set and retainer_id null — this validates cleanly
        # against them. Cheap insurance against a future bug creating an
        # invoice with both/neither parent FK set (see the Phase 7 plan).
        batch_op.create_check_constraint(
            'ck_invoices_kind_parent',
            "(kind IN ('deposit','balance') AND quote_id IS NOT NULL AND retainer_id IS NULL) OR "
            "(kind = 'retainer' AND retainer_id IS NOT NULL AND quote_id IS NULL)",
        )

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('followup_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('followup_sent_at')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('ck_invoices_kind_parent', type_='check')
        batch_op.drop_constraint('fk_invoices_retainer_id', type_='foreignkey')
        batch_op.alter_column('quote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('retainer_id')

    op.drop_table('retainers')
    op.drop_table('retainer_requests')
    op.drop_table('email_logs')
    op.drop_table('job_runs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))

    op.drop_table('clients')
    # ### end Alembic commands ###
