"""add projects, deliverables, approvals; invoice kind

Revision ID: af5fb8bf892e
Revises: 17bfbf9cc4ce
Create Date: 2026-09-15 21:38:20.560247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5fb8bf892e'
down_revision = '17bfbf9cc4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('brief_text', sa.Text(), nullable=True),
    sa.Column('brief_assets', sa.JSON(), nullable=True),
    sa.Column('brief_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        # server_default backfills any existing rows (all Phase 5 invoices
        # are deposits) — dropped right after so it doesn't linger as an
        # implicit DB-level default going forward; the model's own
        # kind="deposit" Python default is what new rows actually rely on.
        batch_op.add_column(sa.Column('kind', sa.String(length=10), nullable=False, server_default='deposit'))
        batch_op.drop_constraint(batch_op.f('invoices_quote_id_key'), type_='unique')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('kind', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('invoices_quote_id_key'), ['quote_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('kind')

    op.drop_table('deliverables')
    op.drop_table('approvals')
    op.drop_table('projects')
    # ### end Alembic commands ###
